import Head from 'next/head';
import Layout from '../components/layout';
import About from './about'


export default function Home() {
  return (
    <Layout home>
      <Head>
        <title>HANA PARK'S PLAYGROUND</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <About/>
    </Layout>
  );
}
